@startuml
title <b>Controller</b>

skinparam ClassFontSize 11
skinparam ClassFontName Verdana



package Controller {
    abstract class GetAndPostCleaner {
        # inputCleaner()
    }

    class ControllerDispatch extends GetAndPostCleaner {
        - $cleanedUpGet : array
        - $cleanedUpPost : array
        - $selectedController : string
        --
        + __construct()
        + __destruct()
        - sessionChecker()
        - unloggedDispatcher()
        - loggedInDispatcher()
    }

    package home {
        class HomeGetController {
            - $homeModel : object
            - $eventIdFinder : object
            - $eventDataGatherer : object
            - $medicArrayBuildOrder : object
            - $homeView : object
            --
            + __construct()
            + displayHomePage()
        }
    }


    package login {
        abstract class LoginCommonController {
            - $loginView : object
            --
            + __construct()
            + __destruct()
            + displayLoginPage()
        }

        class LoginGetController extends LoginCommonController {
            + __destruct()
            + actionReceiver()
        }

        class LoginPostController extends LoginCommonController {
            - $loginModel : object
            --
            + __construct()
            + __destruct()
            + actionReceiver()
        }
    }


    package medic {
        class MedicMainController {
            + __destruct()
            + subContReceiver()
        }

        package allEvents///medic {
            class AllEventsGetController{
                - $medicEventIdFinder : object
                - $medicEventDataGatherer : object
                - $medicEventArrayBuildOrder : object
                - $allEventsView : object
                --
                + __construct()
                + __destruct()
                + displayAllEvents()
            }

        }

        package doc///medic {
            abstract class DocCommonController {
                # $docModel : object
                --
                + __construct()
                + __destruct()
            }

            class DocFormChecker {
                + docFormChecks()
            }


            class DocGetController extends DocGetControllerFunctionsPool {
                # $cleanedUpGet : array
                # $docList : array
                # $speMedicList : array
                # $docOfficeList : array
                # $medicEventList : array
                # $pastEvents : array
                # $futureEvents : array
                # $dataWorkbench : array
                --
                + __construct()
                + __destruct()
                + actionReceiver()
                - displayAllDocList()
                - displayOneDoc()
                - showEventsWithOneDoc()
                - showDocAddForm()
                - showDocEditForm()
                - showDocDeleteForm()
            }


            abstract class DocGetControllerFunctionsPool extends DocCommonController {
                + __construct()
                + __destruct()
                # docIDsExtractor()
                # docTitleAddition()
                # docFullNameSentenceCreator()
                # speMedicAdditionToDocs()
                # docOfficeAddition()
                # speMedicBadgeListBuildUp()
                # dateAndTimeCreator()
                # medicEventArrayTimeModifier()
                # timeManagement()
                # eventTimeDispatcher()
                # pastAndFutureEventsTimeSorting()
                # decrTimestampEventSorting()
                # eventsSummaryCreation()
            }


            class DocPostController extends DocCommonController {
                + __construct()
                + __destruct()
                + actionReceiver()
            }
        }

        package docOffice///medic {
            class DocOfficeCommonController {
                # $docOfficeModel : object
                --
                + __construct()
                + __destruct()
            }

            class DocOfficeGetController extends DocOfficeCommonController {
                - $cleanedUpGet : array
                - $docOfficeList : array
                - $speMedicList : array
                -  $medicEventIdFinder : object
                -  $medicEventDataGatherer : object
                -  $medicEventArrayBuildOrder : object
                -  $docOfficeView : object
                --
                + __construct()
                + __destruct()
                + actionReceiver()
                - displayAllDocOfficesList()
                - displayEventsWithOneDocOffice()
            }

            class DocOfficePostController extends DocOfficeCommonController {
                + __construct()
                + __destruct()
                + actionReceiver
            }

        }


        package eventCat///medic {
            abstract class EventCatCommonController {
                # $eventCatModel: object
                --
                + __construct()
                + __destruct()
            }

            class EventCatGetController extends EventCatCommonController {
                - $cleanedUpGet : array
                -  $medicEventIdFinder : object
                -  $medicEventDataGatherer : object
                -  $medicEventArrayBuildOrder : object
                -  $catView : object
                --
                + __construct()
                + __destruct()
                + actionReceiver ()
                + dispAllEventsRegardingOneCat()
            }

            class EventCatPostController extends EventCatCommonController {
                + __construct()
                + __destruct()
                + actionReceiver()
            }
        }

        package medicTheme///medic {
            abstract class MedicThemeCommonController {
                # $medicThemeModel : object
                --
                + __construct()
                + __destruct()
            }

            class MedicThemeGetController extends MedicThemeCommonController {
                - $cleanedUpGet : array
                - $medicThemeList : array
                - $eventIdFinder : object
                - $medicThemeView : object
                --
                + __construct()
                + __destruct()
                + actionReceiver()
                - displayAllMedicThemes()
                - displayAllEventsRegardingOneTheme()
                - medicThemeListBuildUp()
            }
        }


        package speMedic///medic {
            class SpeMedicGetController {
                -  $cleanedUpGet : array
                -  $speMedicList : array
                -  $eventIdFinder : object
                -  $speMedicModel : object
                -  $speView : object
                --
                + __construct()
                + __destruct()
                + actionReceiver()
                - speMedicListBuildUp()
                - displayAllSpeMedics()
                - dispAllEventsRegardingOneSpeMedic()
            }

        }
    }


    package userAccount {
        class UserAccountGetController {
            - $homeModel : object
            - $homeView : object
            --
            + actionReceiver()
        }

        class UserAccountPostController {
            - $homeModel : object
            - $homeView : object
            --
            + actionReceiver()
        }
    }
}


@enduml