@startuml

skinparam ClassFontSize 11
skinparam ClassFontName Verdana

page 1x2

together {
    package Controller {
        abstract class GetAndPostCleaner {
            # inputCleaner()
        }

        class ControllerDispatch extends GetAndPostCleaner {
            - $cleanedUpGet : array
            - $cleanedUpPost : array
            - $selectedController : string
            --
            + __construct()
            - sessionChecker()
            - unloggedDispatcher()
            - loggedInDispatcher()
        }


        package common///controller {

        }


        package home///controller {
            class HomeGetController {
                - $homeModel : object
                - $eventIdFinder : object
                - $eventDataGatherer : object
                - $medicArrayBuildOrder : object
                - $homeView : object
                --
                + __construct()
                + displayHomePage()
            }
        }


        package login///controller {
            abstract class LoginCommonController {
                - $loginView : object
                --
                + __construct()
                + displayLoginPage()
            }

            class LoginGetController extends LoginCommonController {
                + actionReceiver()
            }

            class LoginPostController extends LoginCommonController {
                - $loginModel : object
                --
                + __construct()
                + actionReceiver()
            }
        }


        package medic///controller {
            class MedicMainController {
                + subContReceiver()
            }

            package allEvents///medic///controller {

            }

            package doc///medic///controller {
                abstract class DocCommonController {
                    # $docModel : object
                    --
                    +__construct()
                }

                class DocGetController extends DocCommonController {
                    - $docView : object
                    - $cleanedUpGet : array
                    - $docList : array
                    - $speMedicList : array
                    --
                    + __construct()
                    + actionReceiver()
                    - displayAllDocList()
                    - displayOneDoc()
                    - docIDsExtractor()
                    - showEventsWithOneDoc()
                    - docTitleAddition()
                    - docFullNameSentenceCreator()
                    - speMedicAdditionToDocs()
                    - speMedicBadgeListBuildUp()
                }

                class DocPostController extends DocCommonController {
                    + __construct()
                    + actionReceiver()
                }
            }

            package docOffice///medic///controller {

            }

            package speMedic///medic///controller {

            }
        }


        package userAccount///controller {
            class UserAccountGetController {
                - $homeModel : object
                - $homeView : object
                --
                + actionReceiver()
            }

            class UserAccountPostController {
                - $homeModel : object
                - $homeView : object
                --
                + actionReceiver()
            }
        }
    }



    package Model {
        package common///model {
            abstract class ModelInChief {
                # $pdo : object
                #  $query : object
                --
                + __construct()
                # pdoInit()
                # stmtWhereBuilder()
                # pdoPreparedSelectExecute()
                # pdoRawSelectExecute()
                # pdoEventSelectMultiQuery()
                # pdoPreparedInsertUpdateDeleteExecute()
            }

        }


        package home///model {
            class HomeModel extends ModelInChief {

            }
        }


        package login///model {
            class LoginModel extends ModelInChief {
                + checkUserLogs()
            }
        }


        package medic///model {
            package allEvents///medic///model {

            }


            package doc///medic///model {
                class DocModel extends ModelInChief {
                    + __construct()
                    + gatherAllDocs()
                    + getOneDoc()
                    + gatherDocSpeMedicRelation()
                }

            }


            package doc///medic///model {

            }


            package eventDataGatherer///medic///model {
                abstract class EventDataGathererPdoManager extends ModelInChief {
                    # $pdoBufferArray : array
                    --
                    + __construct()
                    # pdoBufferArrayReinit()
                    # pdoStmtAndDestInsertionInCue()
                    # pdoStmtAndDestProcessing()
                    # pdoQueryExec()
                    # pdoResultWriter()
                }

                abstract class EventDataHelpers extends EventDataGathererPdoManager{
                    + __construct()
                    - dataStoreArrayPrepPhase1()
                    - dataStoreArrayPrepPhase2()
                    # gatherAll()
                    # dualColumnGatherAll()
                    # gatherAllFromUsagePhase()
                    # idExtractor()
                    # docIDExtractor()
                }

                abstract class SpecificStmtStore extends EventDataHelpers {
                    + __construct()
                    # medicEventList()
                    # docList()
                    # docOfficeList()
                    # prescPharmaListOnlyOrdoPharmaIds()
                    # ordoVaxSlotsOnlyOrdoVaxIds()
                    # treatPharmaNames()
                    # medicAffectNames()
                    # medicEventAffectsRelation()
                    # medicEventThemesRelation()
                    # medicEventSpemedicRelation()
                }

                class EventDataGatherer extends SpecificStmtStore {
                    # $dataStore : array
                    # $eventsIdList : array
                    --
                    + __construct()
                    + eventIdReceiver()
                    - gatherWave1PdoPrep()
                    - idExtractionFromWave1()
                    - gatherWave2PdoPrep()
                    - idExtractionFromWave2()
                    - gatherWave3PdoPrep()
                    - idExtractionFromWave3()
                    - gatherWave4PdoPrep()
                    - idExtractionFromWave4()
                    - gatherWave5PdoPrep()
                    - idExtractionFromWave5()
                    - gatherWave6PdoPrep()
                    - idExtractionFromWave6()
                    - gatherWave7PdoPrep()
                }
            }


            package eventIdFinder///medic///model {
                class EventIdFinder extends ModelInChief {
                    + __construct()
                    + comingEventsIds()
                    + eventsIdsByUserId()
                    + eventsIdsFromOneDocId()
                    + onlyOneEvent()
                }

            }


            package speMedic///medic///model {

            }
        }

        package userAccount///model {

        }
    }

    package Processor {
        package medic///processor {
            class MedicArrayBuildOrder {
                - $originalDataStore : array
                - $dataWorkbench : array
                - $objectStore : array
                - $processedDataArray : array
                --
                + __construct()
                + eventDataReceiver()
                - dateAndTimeCreator()
                - eventStartingManager()
                - prescManager()
                - ordoManager()
                - diagManager()
                - careSessionsManager()
                - vaxSessionsManager()
                - eventEndingManager()
            }

            package care///medic///processor {
                class CareSessionsOrganizer {
                    - $careSessionsList : array
                    - $careSessionElements : array
                    --
                    + careSessionsGeneralBuildOrder()
                    - careSessionsContentOrganizer()
                    - careElementsAddition()
                }
            }

            package diag///medic///processor {
                class DiagConclusionsOrganizer {
                    - $diagConclusions : array
                    - $medicAffectList : array
                    --
                    + diagConclusionsGeneralBuildOrder()
                    - diagConclusionsOrganizer()
                    - diagConclusionsMerge()
                }

                class DiagListOrganizer {
                    - $diagList : array
                    - $diagCheckpoints : array
                    - $diagThemes : array
                    - $diagSymptoms : array
                    - $diagConclusions : array
                    - $ordoGlobalArray : array
                    --
                    + diagListArrayGeneralBuildOrder()
                    - diagListOrganizer()
                    - checkpointsAddition()
                    - themesAddition()
                    - symptomsAddition()
                    - conclusionsAddition()
                    - ordoAddition()
                }

                class DiagThemesOrganizer {
                    - $diagMedicThemesRelation : array
                    - $medicThemeList : array
                    --
                    + diagThemesGeneralBuildOrder()
                    - diagThemeMerge()
                }
            }

            package event///medic///processor {
                class EventDataOrganizer {
                    - $eventArray : array
                    - $dateAndTime : array
                    - $docOfficeList : array
                    - $medicEventThemesRelation : array
                    - $medicEventSpemedicRelation : array
                    - $docSpemedicRelation : array
                    - $speMedicFullList : array
                    - $docList : array
                    --
                    + eventGeneralBuildOrder()
                    - contentOrganizer()
                    - docTitleAndFullNameAddition()
                    - docTitleAddition()
                    - docFullNameSentenceCreator()
                    - docSpeMedicAddition()
                    - docSpeMedicIdAdder()
                    - docSpeMedicAdder()
                    - timeManagement()
                    - eventThemesAddition()
                    - eventSpeMedicAddition()
                    - docOfficeDataAdder()
                }

                class EventFinalContentMerger {
                    - $eventArray : array
                    - $todayEarlyTimestamp : int
                    - $diagList : array
                    - $careSessions : array
                    - $futureEvents : array
                    - $pastEvents : array
                    - $timeSortedEvents : array
                    --
                    + eventContentMerger()
                    - diagContentMerger()
                    - careSessionsContentMerger()
                    - eventTimeDispatcher()
                    - pastAndFutureEventsTimeSorting()
                    - incrTimestampEventSorting()
                    - decrTimestampEventSorting()
                }
            }

            package ordo///medic///processor {
                class OrdoGatherAndSorting {
                    - $ordoLabo : array
                    - $ordoPharma : array
                    - $ordoVax : array
                    - $ordoSight : array
                    - $ordoGlobalArray : array
                    --
                    + ordoArrayGeneralBuildOrder()
                    - allInOneArray()
                    - timestampSorting()
                }

                class OrdoLaboOrganizer {
                    - $ordoLaboList : array
                    - $dateAndTime : array
                    - $prescOrdoLabo : array
                    - $ordoLaboSlots : array
                    --
                    + ordoLaboGeneralBuildOrder()
                    - ordoLaboContentOrganizer()
                    - timeManagement()
                    - prescAdder()
                    - slotsAdder()
                }

                class OrdoPharmaOrganizer {
                    - $ordoPharmaList : array
                    - $dateAndTime : array
                    - $prescOrdoPharma : array
                    --
                    + ordoPharmaGeneralBuildOrder()
                    - timeManagement()
                    - prescAdder()
                }

                class OrdoSightOrganizer {
                    - $ordoSightList : array
                    - $dateAndTime : array
                    --
                    + ordoSightGeneralBuildOrder()
                    - ordoSightContentOrganizer()
                    - glassOrganizer()
                    - lensOrganizer()
                    - timeManagement()
                    - glassAndLensOrdoSentenceBuilder()
                    - perEyeSentenceBuilder()
                    - roundNumberExtender()
                }

                class OrdoVaxOrganizer {
                    - $ordoVaxList : array
                    - $dateAndTime : array
                    - $prescOrdoVax : array
                    - $ordoVaxSlots : array
                    --
                    + ordoVaxGeneralBuildOrder()
                    - ordoVaxContentOrganizer()
                    - timeManagement()
                    - prescAdder()
                    - slotsAdder()
                }

            }

            package presc///medic///processor {
                class PrescOrdoLaboOrganizer {
                    - $prescLaboList : array
                    - $prescLaboElements : array
                    --
                    + prescOrdoLaboGeneralBuildOrder()
                    - prescContentOrganizer()
                    - prescElementsAddition()
                }

                class PrescOrdoPharmaOrganizer {
                    - $prescPharmaList : array
                    - $treatPharmaList : array
                    - $treatPharmaRoleOnAffect : array
                    - $medicAffectList : array
                    --
                    + prescOrdoPharmaGeneralBuildOrder()
                    - prescTreatContentOrganizer()
                    - treatContentOrganizer()
                    - roleContentOrganizer()
                    - affectContentOrganizer()
                    - roleAndAffectMerge()
                    - prescAndRoleMerge()
                    - prescAndTreatMerge()
                }

                class PrescOrdoVaxOrganizer {
                    - $prescVaxList : array
                    - $treatPharmaList : array
                    --
                    + prescOrdoVaxGeneralBuildOrder()
                    - treatmentAdder()
                }
            }

            package vax///medic///processor {
                class VaxSessionsOrganizer {
                    - $vaxSessionsList : array
                    - $vaxSessionsSideEffects : array
                    --
                    + vaxSessionsGeneralBuildOrder()
                    - vaxSessionsContentOrganizer()
                    - vaxSideEffectsAddition()
                }

            }
        }
    }

    package View {
        package common///view {
            abstract class ViewInChief {
                # $topMainLayoutHTML : string
                # $bottomMainLayoutHTML : string
                # $pageContent : string
                --
                # topMainLayoutAssembly()
                # bottomMainLayoutAssembly()
                # pageSetup()
                # pageDisplay()
            }
        }

        package home///view {
            class HomePageBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $eventsData : array
                - $builtContentHTML : string
                - $futureEventsHTML : string
                - $eventsBuilder : object
                --
                + __construct()
                + dataReceiver()
                - buildOrder()
            }

        }

        package login///view {
            class LoginPageBuilder extends ViewInChief {
                - $pageSettingsList : array
                --
                + __construct()
                + buildOrder()
            }
        }

        package medic///view {
            package allEvents///medic///view  {

            }

            package doc///medic///view {
                package docList///doc///medic///view {
                    class DocListPageBuilder extends ViewInChief {
                        - $pageSettingsList : array
                        - $builtContentHTML : string
                        - $docList : array
                        - $speMedicBadgeList : array
                        --
                        + __construct()
                        + buildOrder()
                        - docCardsBuilder()
                        - cardTop()
                        - cardSpeMedicBadgesBuilder()
                        - cardBottom()
                        - addDocButton()
                        - speMedicBadgesBuilder()
                    }
                }

                package eventWithOneDoc///doc///medic///view {
                    class EventsWithOneDocPageBuilder extends ViewInChief {
                        - $pageSettingsList : array
                        - $eventsData : array
                        - $builtContentHTML : string
                        - $pastEventsHTML : string
                        - $futureEventsHTML : string
                        --
                        + __construct()
                        + dataReceiver()
                        - buildOrder()
                    }
                }

                package oneDoc///doc///medic///view {
                    class OneDocPageBuilder extends ViewInChief {
                        - $pageSettingsList : array
                        - $builtContentHTML : string
                        - $docDataArray : array
                        - $speMedicBadgeList : array
                        --
                        + __construct()
                        + dataReceiver()
                        - buildOrder()
                    }

                }
            }

            package docOffice///medic///view {

            }

            package eventsBuilder///medic///view {
                class EventsBuilder extends EventsBuilderFunctionPool {
                    - $eventsData : array;
                    - $allEventsHTMLArray : array;
                    - $allEventsFullHTML : string;
                    - $diagAccordionObj : object;
                    --
                    + __construct()
                    + eventBuildOrder()
                }

                abstract class EventsBuilderFunctionPool {
                    # eventAccordStart()
                    # eventAccordHeaderStart()
                    # docSpeMedicBadges()
                    # attendedPro()
                    # replacedPro()
                    # eventDateTime()
                    # eventDocOffice()
                    # eventSubject()
                    # eventCategory()
                    # medicThemeBadges()
                    # eventMedicTheme()
                    # eventContentButton()
                    # eventAccordHeaderEnd()
                    # eventAccordBodyStart()
                    # eventFullAddrAccordStart()
                    # eventFullAddrAccordContent()
                    # eventFullAddrAccordEnd()
                    # eventAccordComment()
                    # eventAccordBodyEnd()
                    # eventAccordEnd()
                }

                package diag///eventsBuilder///medic///view {
                    class DiagBuilder extends DiagBuilderFunctionsPool {
                        - $pharmaOrdoObj : object
                        - $glassOrdoObj : object
                        - $lensOrdoObj : object
                        - $laboOrdoObj : object
                        - $vaxOrdoObj : object
                        --
                        + __construct()
                        + diagBuilder()
                        - pharmaOrdo()
                        - glassOrdo()
                        - lensOrdo()
                        - laboOrdo()
                        - vaxOrdo()
                    }

                    abstract class DiagBuilderFunctionsPool
                    {
                        # diagAccordionStart()
                        # diagSymptomsBuilder()
                        # diagBetweenSymptAndChecks()
                        # diagChecks()
                        # diagBetweenChecksAndConclu()
                        # diagConclu()
                        # sickDetailedStatusBadge()
                        # diagComment()
                        # diagAccordionEnd()
                    }

                }

                 package ordo///eventsBuilder///medic///view {
                    package glass///ordo///eventsBuilder///medic///view {
                        class GlassOrdoBuilder {
                            + ordoBuilder()
                        }

                    }

                    package labo///ordo///eventsBuilder///medic///view {
                        class LaboOrdoBuilder extends LaboOrdoBuilderFunctionsPool
                        {
                            - $prescLaboObj : object
                            --
                            + __construct()
                            + ordoBuilder()
                        }

                        abstract class LaboOrdoBuilderFunctionsPool {
                            # ordoLaboAccordionStart()
                            # ordoLaboAccordionEnd()
                        }
                    }

                    package lens///ordo///eventsBuilder///medic///view {
                        class LensOrdoBuilder {
                            + ordoBuilder()
                        }

                    }

                    package pharma///ordo///eventsBuilder///medic///view {
                        class PharmaOrdoBuilder extends PharmaOrdoBuilderFunctionsPool
                        {
                            - $pharmaPrescObj : object
                            --
                            + __construct()
                            + ordoBuilder()
                        }

                        abstract class PharmaOrdoBuilderFunctionsPool
                        {
                            # ordoPharmaStarter()
                            # ordoPharmaComment()
                            # ordoPharmaEnd()
                        }
                    }

                    package vax///ordo///eventsBuilder///medic///view {
                        class VaxOrdoBuilder extends VaxOrdoBuilderFunctionsPool {
                            - $prescVaxObj : object
                            --
                            + __construct()
                            + ordoBuilder()
                        }

                        abstract class VaxOrdoBuilderFunctionsPool {
                            # ordoVaxStarter()
                            # ordoComment()
                            # ordoVaxEnd()
                        }

                    }
                }

                package presc///eventsBuilder///medic///view {
                    package labo///presc///eventsBuilder///medic///view {
                        class PrescLaboBuilder extends PrescLaboBuilderFunctionsPool {
                            + prescBuilder()
                        }

                        abstract class PrescLaboBuilderFunctionsPool {
                            # prescStarter()
                            # prescComment()
                            # prescEnd()
                        }
                    }

                    package pharma///presc///eventsBuilder///medic///view {
                        class PharmaPrescBuilder {
                            + prescBuilder()
                        }
                    }

                    package vax///presc///eventsBuilder///medic///view {
                        class PrescVaxBuilder {
                            + prescBuilder()
                        }
                    }
                }

            }
        }

        package userAccount///view {

        }

    }
}




@enduml