@startuml
title <b>View</b>

skinparam ClassFontSize 11
skinparam ClassFontName Verdana



package View {
    package View_/_common {
        abstract class ViewInChief {
            # $pageContent : string
            --
            + __construct()
            # globalLayoutAssembly()
            # pageDisplay()
        }
    }

    package View_/_home {
        class HomePageBuilder extends ViewInChief {
            - $pageSettingsList : array
            - $contentSettingsList : array
            - $futureEventsContentHTML : string
            --
            + __construct()
            + __destruct()
            - pageElementsSettingsList()
            - pageElementsStringReplace()
            + buildOrder()
            - futureEventsBuilder()
            - contentElementsSettingsList()
            - contentElementsStringReplace()
        }
    }

    package View_/_login {
        class LoginPageBuilder extends ViewInChief {
            - $pageSettingsList : array
            --
            + __construct()
            + __destruct()
            # pageSetup()
            + buildOrder()
        }
    }

    package View_/_medic {
        package View_/_medic_/_allEvents {
            class AllEventsPageBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $contentSettingsList : array
                - $eventsContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - allEventsBuilder()
                - futureEventsBuilder()
                - pastEventsBuilder()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }
        }

        package View_/_medic_/_doc {
            package View_/_medic_/_doc_/_docList {
                class DocListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $docList : array
                    - $speMedicBadgeList : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - docCardsListBuilder()
                    - docCardSpeMedicBadgeBuilder()
                    - speMedicBadgesListBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package View_/_medic_/_doc_/_eventsWithOneDoc {
                class EventsWithOneDocPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsData : array
                    - $eventsContent : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - allEventsBuilder()
                    - futureEventsBuilder()
                    - pastEventsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package View_/_medic_/_doc_/_generalDocForm {
                class DocAddFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $formTemplate : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - formConfLauncher()
                    - formActionAndTitleSetup()
                    - checkStatusSetup()
                    - namesSetup()
                    - telAndMailSetup()
                    - webLinksSetup()
                    - commentsSetup()
                    - formButtonsSetup()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

                class DocDeleteFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $docData : array
                    - $formTemplate : string
                    - $checkStatusArray : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - formConfLauncher()
                    - formActionAndTitleSetup()
                    - checkStatusConverter()
                    - checkStatusSetup()
                    - namesSetup()
                    - telAndMailSetup()
                    - webLinksSetup()
                    - commentsSetup()
                    - formButtonsSetup()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

                class DocEditFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $docData : array
                    - $formTemplate : string
                    - $checkStatusArray : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - formConfLauncher()
                    - formActionAndTitleSetup()
                    - checkStatusConverter()
                    - checkStatusSetup()
                    - namesSetup()
                    - telAndMailSetup()
                    - webLinksSetup()
                    - commentsSetup()
                    - formButtonsSetup()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

                class DocFailedAddFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $docData : array
                    - $checksArray : array
                    - $formTemplate : string
                    - $checkStatusArray : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder
                    - formConfLauncher()
                    - formActionAndTitleSetup()
                    - checkStatusConverter()
                    - checkStatusSetup()
                    - validityStatusConverter()
                    - namesSetup()
                    - telAndMailSetup()
                    - webLinksSetup()
                    - commentsSetup()
                    - formButtonsSetup()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

                class DocFailedEditFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $docData : array
                    - $formTemplate : string
                    - $checksArray : array
                    - $docID : string
                    - $checkStatusArray : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - formConfLauncher()
                    - formActionAndTitleSetup()
                    - checkStatusConverter()
                    - checkStatusSetup()
                    - validityStatusConverter()
                    - namesSetup()
                    - telAndMailSetup()
                    - webLinksSetup()
                    - commentsSetup()
                    - formButtonsSetup()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

            }

            package View_/_medic_/_doc_/_oneDoc {
                class OneDocPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $docDataArray : array
                    - $modifButtonHTML : string
                    - $speMedicBadgesHTML : string
                    - $contactContentHTML : string
                    - $commentPortionHTML : string
                    - $medicEventsReportHTML : string
                    - $docOfficeCardsHTML : string
                    - $docModifModalHTML : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - modifButtonBuilder()
                    - speMedicBadgesBuilder()
                    - contactContentBuilder()
                    - phoneAndMailContentBuilder()
                    - websitesContentBuilder()
                    - commentPortionBuilder()
                    - medicEventsReportBuilder()
                    - docOfficeCardsBuilder()
                    - docModifModalBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package View_/_medic_/_doc_/_speMedicDocOfficeForm {
                class SpeMedicDocOfficeFormPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    # $pageContent : string
                    - $formTemplate : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }
        }

        package View_/_medic_/_docOffice {
            package allEventsRegrdOneDocOffice {
                class AllEventsRegrdOneDocOfficePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsContent : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - allEventsBuilder()
                    - futureEventsBuilder()
                    - pastEventsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

            }

            package docOfficeList {
                class DocOfficeListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $docOfficeList : array
                    - $docOfficeCardsListHTML : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - docOfficeCardsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }
        }

        package View_/_medic_/_eventsCats {
            package allEventsRegardingOneCat {
                class AllEventsRegardingOneCatPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsContent : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - allEventsBuilder()
                    - futureEventsBuilder()
                    - pastEventsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package eventCatsList {
                class EventCatsListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventCatCardsHTML : string
                    - $eventCatsList : array
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - eventCatCardsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }
        }

        package View_/_medic_/_eventsBuilder {
            class EventsBuilder {
                - $eventsData : array
                - $allEventsHTMLArray : array
                - $allEventsFullHTML : string
                --
                + __destruct()
                + eventBuildOrder()
            }

            package eventBodyContent {
                class EventBodyContentBuilder {
                    + __destruct()
                    + buildOrder()
                }

                package eventBodyContent_/_eventContent {
                    class EventBodyContentBuilder {
                        + __destruct()
                        + buildOrder()
                    }

                    package eventContent_/_care {
                        package care_/_phase {

                        }

                        package care_/_session {
                            class CareSessionBuilder {
                                + __destruct()
                                + buildOrder()
                            }
                        }
                    }

                    package eventContent_/_diag {
                        class DiagBuilder {
                            + __destruct()
                            + buildOrder()
                        }

                        package diag_/_checkpointsLiElements {
                            class CheckpointsLiElementsBuilder {
                                + __destruct()
                                + buildOrder()
                            }
                        }

                        package diag_/_conclusionsLiElements {
                            class ConclusionsLiElementsBuilder {
                                + __destruct()
                                + buildOrder()
                                - sickDetailedStatusTranslation()
                            }
                        }

                        package diag_/_ordo {
                            package ordo_/_glass {
                                class GlassOrdoBuilder {
                                    + __destruct()
                                    + ordoBuilder()
                                }
                            }

                            package ordo_/_labo {
                                class LaboOrdoBuilder {
                                    + __destruct()
                                    + ordoBuilder()
                                }
                            }

                            package ordo_/_lens {
                                class LensOrdoBuilder {
                                    + __destruct()
                                    + ordoBuilder()
                                }
                            }

                            package ordo_/_pharma {
                                class PharmaOrdoBuilder {
                                    + __destruct()
                                    + ordoBuilder()
                                }

                            }

                            package ordo_/_vax {
                                class VaxOrdoBuilder {
                                    + __destruct()
                                    + ordoBuilder()
                                }
                            }
                        }

                        package diag_/_symptomsLiElements {
                            class SymptomsLiElementsBuilder {
                                + __destruct()
                                + ordoBuilder()
                            }
                        }

                    }

                    package eventContent_/_eventAddress {
                        class EventAddressBuilder {
                            + __destruct()
                            + buildOrder()
                            - eventFullAddrAccordContent()
                        }
                    }

                    package eventContent_/_eventComment {
                        class EventCommentBuilder {
                            + __destruct()
                            + buildOrder()
                        }
                    }
                }
            }

            package eventHeaderContent {
                class EventHeaderContentBuilder {
                    + __destruct()
                    + buildOrder()
                }

                package eventHeaderContent_/_eventAttendedDoc {
                    class EventAttendedDocBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventCategory {
                    class EventCategoryBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventDateTime {
                    class EventDateTimeBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventDateOffice {
                    class EventDocOfficeBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventReplacedDoc {
                    class EventReplacedDocBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventSubject {
                    class EventSubjectBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }

                package eventHeaderContent_/_eventThemes {
                    class EventThemesBuilder {
                        + __destruct()
                        + buildOrder()
                    }
                }
            }
        }

        package View_/_medic_/_medicTheme {
            package medicTheme_/_allEventsRegrdOneTheme {
                class AllEventsRegrdOneThemePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsContent : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - allEventsBuilder()
                    - futureEventsBuilder()
                    - pastEventsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package medicTheme_/_medicThemeList {
                class MedicThemeListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $medicThemeList : array
                    - $medicThemeCardListHTML : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - medicThemeCardsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }
        }

        package View_/_medic_/_speMedic {
            package speMedic_/_AllEventsRegrdOneSpe {
                class AllEventsRegardOneSpePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsContent : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - allEventsBuilder()
                    - futureEventsBuilder()
                    - pastEventsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }
            }

            package speMedic_/speMedicList {
                class SpeMedicListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $speMedicList : array
                    - $speMedicCardListHTML : string
                    --
                    + __construct()
                    + __destruct()
                    - pageElementsSettingsList()
                    - pageElementsStringReplace()
                    + buildOrder()
                    - speMedicCardsBuilder()
                    - contentElementsSettingsList()
                    - contentElementsStringReplace()
                }

            }
        }
    }

    package View_/_userAccount {
        package userAccount_/_userForm {
            class DelFormBuilder extends ViewInChief {
                - $userData : array
                - $transformList : array
                - $pageSettingsList : array
                - $contentSettingsList : array
                # $pageContent : string
                - $mainFieldsSettingsList : array
                - $mainFieldsContent : string
                - $buttonBoxSettingsList : array
                - $buttonBoxContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - dataTransfo()
                - genderTransfo()
                - birthDateTransfo()
                - mainFieldsSettingsList()
                - mainFieldsStringReplace()
                - buttonBoxSettingsList()
                - buttonBoxStringReplace()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }

            class EditFormBuilder extends ViewInChief {
                - $userData : array
                - $transformList : array
                - $pageSettingsList : array
                - $contentSettingsList : array
                # $pageContent : string
                - $mainFieldsSettingsList : array
                - $mainFieldsContent : string
                - $buttonBoxSettingsList : array
                - $buttonBoxContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - dataTransfo()
                - genderTransfo()
                - birthDateTransfo()
                - mainFieldsSettingsList()
                - mainFieldsStringReplace()
                - buttonBoxSettingsList()
                - buttonBoxStringReplace()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }

            class EditPwdFormBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $contentSettingsList : array
                # string $pageContent : string
                - $pwdFieldSettingsList : array
                # $pwdFieldContent : string
                - $buttonBoxSettingsList : array
                - $buttonBoxContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - pwdFieldSettingsList()
                - pwdFieldStringReplace()
                - buttonBoxSettingsList()
                - buttonBoxStringReplace()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }

            class FailedEditFormBuilder extends ViewInChief {
                - $userData : array
                - $checksArray : array
                - $transformList : array
                - $pageSettingsList : array
                - $contentSettingsList : array
                # $pageContent : string
                - $mainFieldsSettingsList : array
                - string $mainFieldsContent : string
                - $buttonBoxSettingsList : array
                - $buttonBoxContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - dataTransfo()
                - genderTransfo()
                - validityStatusConverter()
                - mainFieldsSettingsList()
                - mainFieldsStringReplace()
                - buttonBoxSettingsList()
                - buttonBoxStringReplace()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }

            class FailedEditPwdFormBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $contentSettingsList : array
                # $pageContent : string
                - $cleanedUpPost : array
                - $checksArray : array
                - $pwdFieldSettingsList : array
                # $pwdFieldContent : string
                - $buttonBoxSettingsList : array
                - $buttonBoxContent : string
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - pwdFieldSettingsList()
                - pwdFieldStringReplace()
                - validityStatusConverter()
                - validityStatusStringReplacer()
                - buttonBoxSettingsList()
                - buttonBoxStringReplace()
                - contentElementsSettingsList()
                - contentElementsStringReplace()
            }
        }

        package userAccount_/_userPage {
            class UserAccountPageBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $contentSettingsList : array
                - $userData : array
                - $transformList : array
                --
                + __construct()
                + __destruct()
                - pageElementsSettingsList()
                - pageElementsStringReplace()
                + buildOrder()
                - dataTransfo()
                - genderTransfo()
                - birthDateTransfo()
                - ageCalc()
                - accountCreationDateTransfo()
                - isAdminDivCreation()
                - modifButtonCreation()
                - contentElementsSettingsList()
                contentElementsStringReplace()
            }
        }
    }
}

ViewInChief -[hidden]-> AllEventsPageBuilder

AllEventsRegrdOneThemePageBuilder -[hidden]-> MedicThemeListPageBuilder

SpeMedicListPageBuilder -[hidden]-> AllEventsRegardOneSpePageBuilder

EventHeaderContentBuilder -[hidden]-> EventThemesBuilder
EventThemesBuilder -[hidden]-> EventSubjectBuilder
EventSubjectBuilder -[hidden]-> EventReplacedDocBuilder
EventReplacedDocBuilder -[hidden]-> EventDateTimeBuilder
EventDateTimeBuilder -[hidden]-> EventDocOfficeBuilder
EventDocOfficeBuilder -[hidden]-> EventCategoryBuilder
EventCategoryBuilder -[hidden]-> EventAttendedDocBuilder

EventBodyContentBuilder -[hidden]-> AllEventsPageBuilder

EventCommentBuilder -[hidden]-> EventAddressBuilder
EventAddressBuilder -[hidden]-> CareSessionBuilder

DiagBuilder -[hidden]-> SymptomsLiElementsBuilder
SymptomsLiElementsBuilder -[hidden]-> CheckpointsLiElementsBuilder
CheckpointsLiElementsBuilder -[hidden]-> ConclusionsLiElementsBuilder

PharmaOrdoBuilder -[hidden]-> GlassOrdoBuilder
GlassOrdoBuilder -[hidden]-> LensOrdoBuilder
LensOrdoBuilder -[hidden]-> LaboOrdoBuilder
LaboOrdoBuilder -[hidden]-> VaxOrdoBuilder

AllEventsRegrdOneDocOfficePageBuilder -[hidden]-> DocOfficeListPageBuilder

AllEventsRegardingOneCatPageBuilder -[hidden]-> EventCatsListPageBuilder

OneDocPageBuilder -[hidden]-> DocListPageBuilder
DocListPageBuilder -[hidden]-> SpeMedicDocOfficeFormPageBuilder
SpeMedicDocOfficeFormPageBuilder -[hidden]-> EventsWithOneDocPageBuilder


DocAddFormPageBuilder -[hidden]-> DocFailedAddFormPageBuilder
DocFailedAddFormPageBuilder -[hidden]-> DocEditFormPageBuilder
DocEditFormPageBuilder -[hidden]-> DocFailedEditFormPageBuilder
DocFailedEditFormPageBuilder -[hidden]-> DocDeleteFormPageBuilder

EditFormBuilder -[hidden]-> FailedEditFormBuilder
FailedEditFormBuilder -[hidden]-> EditPwdFormBuilder
EditPwdFormBuilder -[hidden]-> FailedEditPwdFormBuilder
FailedEditPwdFormBuilder -[hidden]-> DelFormBuilder


@enduml