@startmindmap archi_v2

skinparam ClassFontSize 11
skinparam ClassFontName Verdana

* diag/

** ordoList/

*** ordo(Pharma)/

**** presc/
***** treatPharma
***** roleOnAffect
***** medicAffect

@endmindmap