@startuml
title <b>View - Medic without Doc</b>

skinparam ClassFontSize 11
skinparam ClassFontName Verdana

package View {
    package common {
        abstract class ViewInChief {
            # $topMainLayoutHTML : string
            # $bottomMainLayoutHTML : string
            # $pageContent : string
            --
            + __construct()
            + __destruct()
            # topMainLayoutAssembly()
            # bottomMainLayoutAssembly()
            # pageSetup()
            # pageDisplay()
        }
    }



    package medic {
        package allEvents///medic {
            class AllEventsPageBuilder extends ViewInChief {
                - $pageSettingsList : array
                - $eventsData : array
                - $builtContentHTML : string
                - $pastEventsHTML : string
                - $futureEventsHTML : string
                - $eventsBuilder : object
                --
                + __construct()
                + __destruct()
                + dataReceiver()
                - buildOrder()
            }
        }

        package docOffice///medic {
            package allEventsRegrdOneDocOffice///docOffice///medic {
                class AllEventsRegrdOneDocOfficePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsData : array
                    - $builtContentHTML : string
                    - $pastEventsHTML : string
                    - $futureEventsHTML : string
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                    + dataReceiver()
                    - buildOrder()
                    - docOfficeCardsBuilder()
                    - cardBuilder()


                }
            }

            package docOfficeList///docOffice///medic {
                class DocOfficeListPageBuilder extends ViewInChief {
                        - $pageSettingsList : array
                        - $builtContentHTML : string
                        - $docOfficeList : array
                        --
                        + __construct()
                        + __destruct()
                        - buildOrder()
                        - docOfficeCardsBuilder()
                        - cardBuilder()
                }
            }
        }

        package eventCats///medic {
            package allEventsRegardingOneCat///eventCats///medic {
                class AllEventsRegardingOneCatPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsData : array
                    - $builtContentHTML : string
                    - $pastEventsHTML : string
                    - $futureEventsHTML : string
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                }
            }

            package eventCatsList///eventCats///medic {
                class EventCatsListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $builtContentHTML : string
                    - $eventCatsList : array
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                    - eventCatCardsBuilder()
                    - cardBuild()
                }
            }
        }


        package medicTheme///medic {
            package allEventsRegrdOneTheme///medicTheme///medic {
                class AllEventsRegrdOneThemePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsData : array
                    - $builtContentHTML : string
                    - $pastEventsHTML : string
                    - $futureEventsHTML : string
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                }
            }

            package medicThemeList///medicTheme///medic {
                class MedicThemeListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $builtContentHTML : string
                    - $medicThemeList : array
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                    - medicThemeCardsBuilder()
                    - cardBuilder()
                }
            }
        }

        package speMedic///medic {
            package AllEventsRegrdOneSpe///speMedic///medic {
                class AllEventsRegardOneSpePageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $eventsData : array
                    - $builtContentHTML : string
                    - $pastEventsHTML : string
                    - $futureEventsHTML : string
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()

                }
            }

            package speMedicList///speMedic///medic {
                class SpeMedicListPageBuilder extends ViewInChief {
                    - $pageSettingsList : array
                    - $builtContentHTML : string
                    - $speMedicList : array
                    --
                    + __construct()
                    + __destruct()
                    + dataReceiver()
                    - buildOrder()
                    - speMedicCardsBuilder()
                    - cardBuilder()
                }
            }
        }
}






@enduml