@startuml
title <b>View - EventsBuilder</b>

skinparam ClassFontSize 11
skinparam ClassFontName Verdana

package View {

    package medic {

    package eventsBuilder///medic {
        class EventsBuilder extends EventsBuilderFunctionPool {
            - $eventsData : array
            - $allEventsHTMLArray : array
            - $allEventsFullHTML : string
            - $diagAccordionObj : object
            --
            + __construct()
            + __destruct()
            + eventBuildOrder()
        }

        abstract class EventsBuilderFunctionPool {
            + __destruct()
            # eventAccordStart()
            # eventAccordHeaderStart()
            # docSpeMedicBadges()
            # attendedPro()
            # replacedPro()
            # eventDateTime()
            # eventDocOffice()
            # eventSubject()
            # eventCategory()
            # medicThemeBadges()
            # eventMedicTheme()
            # eventContentButton()
            # eventAccordHeaderEnd()
            # eventAccordBodyStart()
            # eventFullAddrAccordStart()
            # eventFullAddrAccordContent()
            # eventFullAddrAccordEnd()
            # eventAccordComment()
            # eventAccordBodyEnd()
            # eventAccordEnd()
        }

        package diag///eventsBuilder///medic {
            class DiagBuilder extends DiagBuilderFunctionsPool {
                - $pharmaOrdoObj : object
                - $glassOrdoObj : object
                - $lensOrdoObj : object
                - $laboOrdoObj : object
                - $vaxOrdoObj : object
                --
                + __construct()
                + __destruct()
                + diagBuilder()
                - pharmaOrdo()
                - glassOrdo()
                - lensOrdo()
                - laboOrdo()
                - vaxOrdo()
            }

            abstract class DiagBuilderFunctionsPool
            {
                + __destruct()
                # diagAccordionStart()
                # diagSymptomsBuilder()
                # diagBetweenSymptAndChecks()
                # diagChecks()
                # diagBetweenChecksAndConclu()
                # diagConclu()
                # sickDetailedStatusBadge()
                # diagComment()
                # diagAccordionEnd()
            }
        }

            package ordo///eventsBuilder///medic {
                package glass///ordo///eventsBuilder///medic {
                    class GlassOrdoBuilder {
                        + __destruct()
                        + ordoBuilder()
                    }
                }

            package labo///ordo///eventsBuilder///medic {
                class LaboOrdoBuilder extends LaboOrdoBuilderFunctionsPool
                {
                    - $prescLaboObj : object
                    --
                    + __construct()
                    + __destruct()
                    + ordoBuilder()
                }

                abstract class LaboOrdoBuilderFunctionsPool {
                    + __destruct()
                    # ordoLaboAccordionStart()
                    # ordoLaboAccordionEnd()
                }
            }

            package lens///ordo///eventsBuilder///medic {
                class LensOrdoBuilder {
                    + __destruct()
                    + ordoBuilder()
                }

            }

            package pharma///ordo///eventsBuilder///medic {
                class PharmaOrdoBuilder extends PharmaOrdoBuilderFunctionsPool
                {
                    - $pharmaPrescObj : object
                    --
                    + __construct()
                    + __destruct()
                    + ordoBuilder()
                }

                abstract class PharmaOrdoBuilderFunctionsPool {
                    + __destruct()
                    # ordoPharmaStarter()
                    # ordoPharmaComment()
                    # ordoPharmaEnd()
                }
            }

            package vax///ordo///eventsBuilder///medic {
                class VaxOrdoBuilder extends VaxOrdoBuilderFunctionsPool {
                    - $prescVaxObj : object
                    --
                    + __construct()
                    + __destruct()
                    + ordoBuilder()
                }

                abstract class VaxOrdoBuilderFunctionsPool {
                    + __destruct()
                    # ordoVaxStarter()
                    # ordoComment()
                    # ordoVaxEnd()
                }
            }
        }

        package presc///eventsBuilder///medic {
            package labo///presc///eventsBuilder///medic {
                class PrescLaboBuilder extends PrescLaboBuilderFunctionsPool {
                    + __destruct()
                    + prescBuilder()
                }

                abstract class PrescLaboBuilderFunctionsPool {
                    + __destruct()
                    # prescStarter()
                    # prescComment()
                    # prescEnd()
                }
            }

            package pharma///presc///eventsBuilder///medic {
                class PharmaPrescBuilder {
                    + __destruct()
                    + prescBuilder()
                }
            }

            package vax///presc///eventsBuilder///medic {
                class PrescVaxBuilder {
                    + __destruct()
                    + prescBuilder()
                }
            }
        }
    }
    }


}



EventsBuilder -[hidden]-> DiagBuilderFunctionsPool
DiagBuilder -[hidden]--> PharmaOrdoBuilderFunctionsPool
VaxOrdoBuilder -[hidden]--> PrescVaxBuilder

@enduml