@startuml

left to right direction
actor User as U

rectangle HealthKerd {
    usecase "Afficher tous les rendez-vous à venir" as UC1
    usecase "Afficher tous les rendez-vous" as UC2
    usecase "Afficher tous les rendez-vous liés à un professionnel de santé" as UC3
    usecase "Créer un professionnel de santé" as UC4
    usecase "Modifier un professionnel de santé" as UC5
    usecase "Supprimer un professionnel de santé" as UC6
    usecase "Voir la fiche d'un professionnel de santé" as UC7
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6
U --> UC7

@enduml